### ISSUE TITLE
Code release date?

### ISSUE THREAD

**Issue by MilesTheProwler** [xz-pisces/Inner-body#1]
Hi, when will you release the open-source code ? 

Thanks.

**Comment by xz-pisces** [comment]
Within a few weeks

**Comment by MilesTheProwler** [comment]
Thank you for your kind reply. I have a few questions on your project. Does your project output obj file with fully textured skin ? Secondly, can we test our own dataset on your model? 

Thanks.

**Comment by xz-pisces** [comment]
Q1: No; the code about fully textured skin output will not be released;
Q2: Yes

**Comment by MilesTheProwler** [comment]
Hi, Is it delay for the release date?

**Comment by xz-pisces** [comment]
I'm very sorry, but I've been busy with my CVPR paper recently. I will promptly coordinate with other classmates to ensure it is organized, finalized, and open-sourced. My email is **lxz@tju.edu.cn**, feel free to contact me anytime.

**Comment by xz-pisces** [comment]
@MilesTheProwler. The codes are released.
